name: Pipeline

on:
  schedule:
    # 1. Checagem Rápida
    - cron: '21 * * * *'
    
    # 2. Varredura Completa
    - cron: '21 3 * * *'

  workflow_dispatch: # Execução manual via painel do GitHub
    inputs:
      acao:
        description: 'Selecione a ação:'
        type: choice
        default: 'apenas_tratamento'
        options:
          - 'coleta_e_tratamento'
          - 'apenas_tratamento'
      modo_completo:
        description: 'Forçar varredura completa (coleta)'
        type: boolean
        default: false

jobs:
  executar-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # 1. PASSO DO IMPORTADOR
      # Roda se for agendamento automático OU se a ação manual não for 'apenas_tratamento'
      - name: Executar Script de Importação
        if: ${{ github.event_name == 'schedule' || github.event.inputs.acao == 'coleta_e_tratamento' }}
        run: |
          if [ "${{ github.event.schedule }}" = "21 3 * * *" ] || [ "${{ github.event.inputs.modo_completo }}" = "true" ]; then
            node importador.js --completa
          else
            node importador.js
          fi
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

      # 2. VERIFICA SE O BANCO BRUTO FOI ALTERADO PELO IMPORTADOR
      - name: Verificar se houve alteração em videos_bruto.json
        id: check_bruto
        run: |
          if git diff --name-only | grep -q 'videos_bruto.json'; then
            echo "bruto_alterado=true" >> $GITHUB_OUTPUT
          else
            echo "bruto_alterado=false" >> $GITHUB_OUTPUT
          fi

      # 3. PASSO DO TRATADOR
      # Roda se: o importador alterou o bruto OR se o usuário escolheu 'apenas_tratamento'
      - name: Executar Script de Tratamento (ETL)
        if: ${{ steps.check_bruto.outputs.bruto_alterado == 'true' || github.event.inputs.acao == 'apenas_tratamento' }}
        run: |
          echo "🚀 Executando Tratador de Dados..."
          node tratador.js

      # 4. SALVAR ALTERAÇÕES (AUTO COMMIT)
      # Salva o bruto e/ou o database.json se houver modificações em qualquer um deles
      - name: Salvar alterações no Git (Auto Commit)
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add videos_bruto.json database.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "BOT:UPDATE" && git push)
